
import java.text.ParseException;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Front extends javax.swing.JFrame {
    
    private int flag = 0;
    
    private DadosAgencias dtAg;
    private DadosCliente dtCl;
    private DadosContas dtCt;
    private DadosFuncionarios dtFc;
    
    public Front() {
        initComponents();
        dtAg = new DadosAgencias();
        dtCl = new DadosCliente();
        dtCt = new DadosContas();
        dtFc = new DadosFuncionarios();
        setIn();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        typeConta = new javax.swing.ButtonGroup();
        sex = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pCadConta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtContNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passConta = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        bntAtv = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        txtContaAg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtContaTitu = new javax.swing.JTextField();
        btnIn = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnTSal = new javax.swing.JRadioButton();
        btnTPou = new javax.swing.JRadioButton();
        btnTCorr = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        pCliente = new javax.swing.JPanel();
        cadCliente = new javax.swing.JButton();
        listCliente = new javax.swing.JButton();
        salvCliente = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btnAttCl = new javax.swing.JButton();
        pFunc = new javax.swing.JPanel();
        cadFunc = new javax.swing.JButton();
        listFunc = new javax.swing.JButton();
        salvFunc = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btnAttF = new javax.swing.JButton();
        pConta = new javax.swing.JPanel();
        cadConta = new javax.swing.JButton();
        listConta = new javax.swing.JButton();
        salvConta = new javax.swing.JButton();
        saca = new javax.swing.JButton();
        deposita = new javax.swing.JButton();
        transfere = new javax.swing.JButton();
        btnCadAgn = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        btnAttCt = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        pCadPessoa = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtPessNome = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtPessCPF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEstCivil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPessEsc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPessTel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPessDt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnH = new javax.swing.JRadioButton();
        btnM = new javax.swing.JRadioButton();
        btnPE = new javax.swing.JButton();
        pCadEndereco = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtEndLog = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtEndNum = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEndCdd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEndUF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtEndCEP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtEndBai = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        pCadFunc = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtFuncCTPS = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDtAdm = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtFuncCargo = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        btnFuncGer = new javax.swing.JRadioButton();
        pCadAgencia = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        txtAgcNome = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtAgcNum = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtAgcGer = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        pRemover = new javax.swing.JPanel();
        lblRm = new javax.swing.JLabel();
        txtRemove = new javax.swing.JTextField();
        btnRm = new javax.swing.JButton();
        pListar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListar = new javax.swing.JTextArea();
        pSacDep = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtCtO = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        passCtO = new javax.swing.JPasswordField();
        txtCtD = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();

        buttonGroup1.add(bntAtv);
        buttonGroup1.add(btnIn);

        typeConta.add(btnTSal);
        typeConta.add(btnTCorr);
        typeConta.add(btnTPou);

        sex.add(btnH);
        sex.add(btnM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Conta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Funcionario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Número:");

        jLabel2.setText("Senha:");

        jLabel3.setText("Status da conta:");

        bntAtv.setText("Ativo");
        bntAtv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAtvActionPerformed(evt);
            }
        });

        jLabel4.setText("Número da Agencia:");

        txtContaAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContaAgActionPerformed(evt);
            }
        });

        jLabel5.setText("Cpf do Titular:");

        btnIn.setText("Inativo");

        jLabel6.setText("Tipo da Conta: ");

        btnTSal.setText("Salário");

        btnTPou.setText("Poupança");

        btnTCorr.setText("Corrente");

        jButton4.setText("Ok");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadContaLayout = new javax.swing.GroupLayout(pCadConta);
        pCadConta.setLayout(pCadContaLayout);
        pCadContaLayout.setHorizontalGroup(
            pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadContaLayout.createSequentialGroup()
                        .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContNum)
                            .addComponent(passConta)))
                    .addGroup(pCadContaLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContaAg))
                    .addGroup(pCadContaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContaTitu))
                    .addGroup(pCadContaLayout.createSequentialGroup()
                        .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pCadContaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bntAtv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIn))
                            .addGroup(pCadContaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTSal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTPou)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTCorr)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadContaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(175, 175, 175))
        );
        pCadContaLayout.setVerticalGroup(
            pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtContNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bntAtv)
                    .addComponent(btnIn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtContaAg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtContaTitu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnTSal)
                    .addComponent(btnTPou)
                    .addComponent(btnTCorr))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        cadCliente.setText("Cadastrar");
        cadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClienteActionPerformed(evt);
            }
        });

        listCliente.setText("Listar");
        listCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listClienteActionPerformed(evt);
            }
        });

        salvCliente.setText("Salvar");
        salvCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvClienteActionPerformed(evt);
            }
        });

        jButton9.setText("Remover");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnAttCl.setText("Atualizar");
        btnAttCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttClActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pClienteLayout = new javax.swing.GroupLayout(pCliente);
        pCliente.setLayout(pClienteLayout);
        pClienteLayout.setHorizontalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addComponent(btnAttCl))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        pClienteLayout.setVerticalGroup(
            pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadCliente)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(pClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listCliente)
                    .addComponent(btnAttCl))
                .addGap(18, 18, 18)
                .addComponent(salvCliente)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        cadFunc.setText("Cadastrar");
        cadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFuncActionPerformed(evt);
            }
        });

        listFunc.setText("Listar");
        listFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listFuncActionPerformed(evt);
            }
        });

        salvFunc.setText("Salvar");
        salvFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvFuncActionPerformed(evt);
            }
        });

        jButton8.setText("Remover");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnAttF.setText("Atualizar");
        btnAttF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pFuncLayout = new javax.swing.GroupLayout(pFunc);
        pFunc.setLayout(pFuncLayout);
        pFuncLayout.setHorizontalGroup(
            pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salvFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(btnAttF))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        pFuncLayout.setVerticalGroup(
            pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadFunc)
                    .addComponent(jButton8))
                .addGap(18, 18, 18)
                .addGroup(pFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listFunc)
                    .addComponent(btnAttF))
                .addGap(18, 18, 18)
                .addComponent(salvFunc)
                .addContainerGap(323, Short.MAX_VALUE))
        );

        cadConta.setText("Abrir Conta");
        cadConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadContaActionPerformed(evt);
            }
        });

        listConta.setText("Listar Contas");
        listConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listContaActionPerformed(evt);
            }
        });

        salvConta.setText("Salvar");
        salvConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvContaActionPerformed(evt);
            }
        });

        saca.setText("Sacar");
        saca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacaActionPerformed(evt);
            }
        });

        deposita.setText("Depositar");
        deposita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositaActionPerformed(evt);
            }
        });

        transfere.setText("Transferir");
        transfere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transfereActionPerformed(evt);
            }
        });

        btnCadAgn.setText("Cadastrar Agencia");
        btnCadAgn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadAgnActionPerformed(evt);
            }
        });

        jButton10.setText("Remover Conta");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Remover Agencia");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnAttCt.setText("Atualizar Conta");
        btnAttCt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttCtActionPerformed(evt);
            }
        });

        jButton14.setText("Atualizar Agencia");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pContaLayout = new javax.swing.GroupLayout(pConta);
        pConta.setLayout(pContaLayout);
        pContaLayout.setHorizontalGroup(
            pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContaLayout.createSequentialGroup()
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pContaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cadConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(transfere, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deposita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadAgn)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pContaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnAttCt)
                        .addGap(18, 18, 18)
                        .addComponent(jButton14)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pContaLayout.setVerticalGroup(
            pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadConta)
                    .addComponent(saca)
                    .addComponent(btnCadAgn))
                .addGap(18, 18, 18)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listConta)
                    .addComponent(deposita)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvConta)
                    .addComponent(transfere)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(pContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAttCt)
                    .addComponent(jButton14))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jLabel19.setText("Nome:");

        jLabel20.setText("CPF:");

        jLabel7.setText("Estado Civil:");

        jLabel8.setText("Escolaridade: ");

        jLabel9.setText("Telefone:");

        jLabel10.setText("Data de nascimento:");

        jLabel11.setText("Sexo:");

        btnH.setText("H");

        btnM.setText("M");

        btnPE.setText("Next ->");
        btnPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadPessoaLayout = new javax.swing.GroupLayout(pCadPessoa);
        pCadPessoa.setLayout(pCadPessoaLayout);
        pCadPessoaLayout.setHorizontalGroup(
            pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessNome))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessCPF))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstCivil))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessEsc))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessTel))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPessDt, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                    .addGroup(pCadPessoaLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnM)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadPessoaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPE)
                .addGap(158, 158, 158))
        );
        pCadPessoaLayout.setVerticalGroup(
            pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadPessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtPessNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPessCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEstCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPessEsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPessTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPessDt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnH)
                    .addComponent(btnM))
                .addGap(18, 18, 18)
                .addComponent(btnPE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jLabel13.setText("Logradouro:");

        jLabel14.setText("Número:");

        jLabel15.setText("Cidade:");

        jLabel16.setText("UF:");

        jLabel17.setText("CEP:");

        jLabel18.setText("Bairro:");

        jButton6.setText("Ok");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadEnderecoLayout = new javax.swing.GroupLayout(pCadEndereco);
        pCadEndereco.setLayout(pCadEnderecoLayout);
        pCadEnderecoLayout.setHorizontalGroup(
            pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndLog, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
                    .addGroup(pCadEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndNum))
                    .addGroup(pCadEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndCdd))
                    .addGroup(pCadEnderecoLayout.createSequentialGroup()
                        .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEndUF)
                            .addComponent(txtEndCEP)))
                    .addGroup(pCadEnderecoLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEndBai)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadEnderecoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(174, 174, 174))
        );
        pCadEnderecoLayout.setVerticalGroup(
            pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtEndLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtEndNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtEndCdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16)
                    .addComponent(txtEndUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtEndCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEndBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("CTPS:");

        jLabel21.setText("Data de Admição:");

        jLabel22.setText("Cargo:");

        jButton5.setText("Next ->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnFuncGer.setText("Gerente");

        javax.swing.GroupLayout pCadFuncLayout = new javax.swing.GroupLayout(pCadFunc);
        pCadFunc.setLayout(pCadFuncLayout);
        pCadFuncLayout.setHorizontalGroup(
            pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadFuncLayout.createSequentialGroup()
                        .addComponent(btnFuncGer)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pCadFuncLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncCTPS))
                    .addGroup(pCadFuncLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDtAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(pCadFuncLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFuncCargo)))
                .addContainerGap())
            .addGroup(pCadFuncLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadFuncLayout.setVerticalGroup(
            pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadFuncLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFuncCTPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtDtAdm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22)
                    .addComponent(txtFuncCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFuncGer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel24.setText("Nome:");

        jLabel25.setText("Número:");

        jLabel26.setText("CPF do Gerente:");

        jButton7.setText("Next ->");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pCadAgenciaLayout = new javax.swing.GroupLayout(pCadAgencia);
        pCadAgencia.setLayout(pCadAgenciaLayout);
        pCadAgenciaLayout.setHorizontalGroup(
            pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadAgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadAgenciaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgcNome))
                    .addGroup(pCadAgenciaLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgcNum))
                    .addGroup(pCadAgenciaLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgcGer)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadAgenciaLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(163, 163, 163))
        );
        pCadAgenciaLayout.setVerticalGroup(
            pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadAgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtAgcNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtAgcNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pCadAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtAgcGer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRm.setText("jLabel23");

        btnRm.setText("Ok");
        btnRm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pRemoverLayout = new javax.swing.GroupLayout(pRemover);
        pRemover.setLayout(pRemoverLayout);
        pRemoverLayout.setHorizontalGroup(
            pRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRemove)
                    .addComponent(lblRm, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(btnRm)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pRemoverLayout.setVerticalGroup(
            pRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRm, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRemove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
        );

        txtListar.setColumns(20);
        txtListar.setRows(5);
        jScrollPane1.setViewportView(txtListar);

        javax.swing.GroupLayout pListarLayout = new javax.swing.GroupLayout(pListar);
        pListar.setLayout(pListarLayout);
        pListarLayout.setHorizontalGroup(
            pListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );
        pListarLayout.setVerticalGroup(
            pListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pListarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel23.setText("Valor: R$");

        jLabel27.setText("Conta de destino:");

        jLabel28.setText("Conta de Origem:");

        jLabel29.setText("Senha:");

        passCtO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passCtOActionPerformed(evt);
            }
        });

        jButton12.setText("ok");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSacDepLayout = new javax.swing.GroupLayout(pSacDep);
        pSacDep.setLayout(pSacDepLayout);
        pSacDepLayout.setHorizontalGroup(
            pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSacDepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSacDepLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValor))
                    .addGroup(pSacDepLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCtO))
                    .addGroup(pSacDepLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passCtO))
                    .addGroup(pSacDepLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCtD)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSacDepLayout.createSequentialGroup()
                .addContainerGap(187, Short.MAX_VALUE)
                .addComponent(jButton12)
                .addGap(185, 185, 185))
        );
        pSacDepLayout.setVerticalGroup(
            pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSacDepLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtCtO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(passCtO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pSacDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtCtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(68, 68, 68)
                .addComponent(jButton3)
                .addContainerGap())
            .addComponent(pCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCadConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCadPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCadEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(14, 14, 14)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCadAgencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pSacDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(pFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(33, 33, 33)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(pConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(pCadConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pCadPessoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(pCadEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(226, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pCadFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(pCadAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(323, 323, 323)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(pRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(30, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(pSacDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setIn(){
        pRemover.setVisible(false);
        pConta.setVisible(false);
        pCadConta.setVisible(false);
        pFunc.setVisible(false);
        pCliente.setVisible(false);
        pCadConta.setVisible(false);
        pCadEndereco.setVisible(false);
        pCadFunc.setVisible(false);
        pCadPessoa.setVisible(false);
        pCadAgencia.setVisible(false);
        pListar.setVisible(false);
        pSacDep.setVisible(false);
    }
    
    private void limpar(){
        txtAgcGer.setText("");
        txtAgcNome.setText("");
        txtAgcNum.setText("");
        txtContNum.setText("");
        txtContaAg.setText("");
        txtContaTitu.setText("");
        txtCtD.setText("");
        txtCtO.setText("");
        txtDtAdm.setText("");
        txtEndBai.setText("");
        txtEndCEP.setText("");
        txtEndCdd.setText("");
        txtEndLog.setText("");
        txtEndNum.setText("");
        txtEstCivil.setText("");
        txtEndUF.setText("");
        txtFuncCTPS.setText("");
        txtFuncCargo.setText("");
        txtListar.setText("");
        txtPessCPF.setText("");
        txtPessDt.setText("");
        txtPessEsc.setText("");
        txtPessNome.setText("");
        txtPessTel.setText("");
        txtRemove.setText("");
        txtValor.setText("");
        passConta.setText("");
        passCtO.setText("");
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setIn();
        pConta.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setIn();
        pCliente.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setIn();
        pFunc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cadContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadContaActionPerformed
        setIn();
        pCadConta.setVisible(true);
    }//GEN-LAST:event_cadContaActionPerformed

    private void cadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClienteActionPerformed
        setIn();
        this.flag = 1;
        pCadPessoa.setVisible(true);
    }//GEN-LAST:event_cadClienteActionPerformed

    private void listContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listContaActionPerformed
        setIn();
        StringBuilder strB = new StringBuilder();
        for(Conta c: dtCt.getlContas()){
            strB.append(c.toString()+"\n");
        }
        txtListar.setText(strB.toString());
        pListar.setVisible(true);
    }//GEN-LAST:event_listContaActionPerformed

    private void cadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFuncActionPerformed
       setIn();
       this.flag = 2;
       pCadPessoa.setVisible(true);
    }//GEN-LAST:event_cadFuncActionPerformed

    private void txtContaAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContaAgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContaAgActionPerformed

    private void bntAtvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAtvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntAtvActionPerformed

    private void btnPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPEActionPerformed
        setIn();
        if(this.flag==1||this.flag==11)pCadEndereco.setVisible(true);
        else pCadFunc.setVisible(true);
    }//GEN-LAST:event_btnPEActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setIn();
        pCadEndereco.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCadAgnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadAgnActionPerformed
        setIn();
        this.flag = 3;
        pCadAgencia.setVisible(true);
    }//GEN-LAST:event_btnCadAgnActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setIn();
        pCadEndereco.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Endereco tempEndereco = new Endereco(txtEndLog.getText(),Integer.parseInt(txtEndNum.getText()),txtEndBai.getText(),
                txtEndCdd.getText(),txtEndUF.getText(),txtEndCEP.getText());
        if(this.flag==1){
            Date tempDt = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            try {
                tempDt = sdf.parse(txtPessDt.getText());
            } catch (ParseException ex) {
                tempDt = null;
            }
            Cliente tempCliente = new Cliente(txtPessCPF.getText() ,txtPessNome.getText(),
                    tempEndereco,tempDt,txtEstCivil.getText(),txtPessEsc.getText(),null);
            tempCliente.setTelefone(txtPessTel.getText());
            if(btnH.isSelected()){
                tempCliente.setSexo('H');
            }else tempCliente.setSexo('M');
            this.dtCl.cadastrar(tempCliente);
        }else if(this.flag==2){
            Funcionario f;
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date tempDt;
            try {
                tempDt = sdf.parse(txtPessDt.getText());
            } catch (ParseException ex) {
                tempDt = null;
            }
            if(btnFuncGer.isSelected()){
                f = new Gerente(txtPessNome.getText(),tempEndereco,txtPessCPF.getText(),txtFuncCTPS.getText(),new Date(),null,false);
                f.setCargo("Gerente");
                f.setEstCivil(txtEstCivil.getText());
                f.setEscolaridade(txtPessEsc.getText());
                f.setTelefone(txtPessTel.getText());
                f.setDataNasc(tempDt);
            }
            else{
                f = new Funcionario(txtPessCPF.getText(),txtPessNome.getText(),tempEndereco,txtEstCivil.getText(),txtPessEsc.getText(),
                        txtPessTel.getText(), tempDt,'\0',txtFuncCTPS.getText(),new Date(),txtFuncCargo.getText());
            }
            if(btnH.isSelected()){
                f.setSexo('H');
            }else f.setSexo('M');
            try {
                tempDt = sdf.parse(txtDtAdm.getText());
            } catch (ParseException ex) {
                tempDt = null;
            }
            f.setDataAdm(tempDt);
            this.dtFc.cadastrar(f);
        }else if(this.flag == 3){
            Gerente gr = (Gerente)this.dtFc.buscar(txtAgcGer.getText());
            Agencia tempAgencia = new Agencia(txtAgcNome.getText(),Integer.parseInt(txtAgcNum.getText()),tempEndereco,gr);
            this.dtAg.cadastrar(tempAgencia);
            gr.setAgencia(tempAgencia);
        }else if(this.flag==12){
            Funcionario tf = dtFc.buscar(txtRemove.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            tf.setCPF(txtPessCPF.getText());
            tf.setCTPS(txtFuncCTPS.getText());
            tf.setCargo(txtFuncCargo.getText());
            try {
                tf.setDataNasc(sdf.parse(txtPessDt.getText()));
            } catch (ParseException ex) {}
            tf.setEndereco(tempEndereco);
            tf.setEscolaridade(txtPessEsc.getText());
            tf.setEstCivil(txtEstCivil.getText());
            tf.setNome(txtPessNome.getText());
            tf.setTelefone(txtPessTel.getText());
            if(btnH.isSelected()){
                tf.setSexo('H');
            }else tf.setSexo('M');
        }else if(this.flag==11){
            Cliente tc = dtCl.buscar(txtRemove.getText());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            tc.setCPF(txtPessCPF.getText());
            try {
                tc.setDataNasc(sdf.parse(txtPessDt.getText()));
            } catch (ParseException ex) {}
            tc.setEndereco(tempEndereco);
            tc.setEscolaridade(txtPessEsc.getText());
            tc.setEstCivil(txtEstCivil.getText());
            tc.setNome(txtPessNome.getText());
            if(btnH.isSelected()){
                tc.setSexo('H');
            }else tc.setSexo('M');
            tc.setTelefone(txtPessTel.getText());
        }else if(this.flag==13){
            Agencia ta = dtAg.buscar(Integer.parseInt(txtRemove.getText()));
            ta.setEndereco(tempEndereco);
            ta.setGerente((Gerente)dtFc.buscar(txtAgcGer.getText()));
            ta.setNome(txtAgcNome.getText());
            ta.setNumero(Integer.parseInt(txtAgcNum.getText()));
        }
        setIn();
        limpar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       setIn();
        pRemover.setVisible(true);
        lblRm.setText("Numero da conta");
        this.flag = 1;
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        setIn();
        pRemover.setVisible(true);
        lblRm.setText("CPF do cliente");
        this.flag = 2; 
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        setIn();
        pRemover.setVisible(true);
        lblRm.setText("Numero da agencia");
        this.flag = 3;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        setIn();
        pRemover.setVisible(true);
        lblRm.setText("CPF do funcionario");
        this.flag = 4;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnRmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmActionPerformed
        setIn();
        if(this.flag == 1){dtCt.excluir(Integer.parseInt(txtRemove.getText()));}
        else if(this.flag == 2){dtCl.excluir(txtRemove.getText());limpar();}
        else if(this.flag == 3){dtAg.excluir(Integer.parseInt(txtRemove.getText()));limpar();}
        else if(this.flag == 4){dtFc.excluir(txtRemove.getText());limpar();}
        else if(this.flag == 10){setIn();
            pCadConta.setVisible(true);
        }
        else if(this.flag == 11){
            pCadPessoa.setVisible(true);}
        else if(this.flag == 12){
            pCadPessoa.setVisible(true);
        }
        
    }//GEN-LAST:event_btnRmActionPerformed

    private void salvClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvClienteActionPerformed
        Persistencia p = new Persistencia();
        p.salvar("Clientes.date", this.dtCl);
    }//GEN-LAST:event_salvClienteActionPerformed

    private void salvFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvFuncActionPerformed
        Persistencia p = new Persistencia();
        p.salvar("Funcionario.date", this.dtFc);
    }//GEN-LAST:event_salvFuncActionPerformed

    private void salvContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvContaActionPerformed
        Persistencia p = new Persistencia();
        p.salvar("Contas.date", this.dtCt);
        p.salvar("Agencias.date",this.dtAg);
    }//GEN-LAST:event_salvContaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(this.flag==10){
            Conta tc = dtCt.buscar(Integer.parseInt(txtRemove.getText()));
            tc.setNumero(Integer.parseInt(txtContNum.getText()));
            tc.setSenha(passConta.getText());
            tc.setAgencia(dtAg.buscar(Integer.parseInt(txtContaAg.getText())));
            return;
        }
        Conta tempConta;
        if(btnTCorr.isSelected()){
            tempConta = new ContaCorrente();
        }else if(btnTPou.isSelected()){
            tempConta = new ContaPoupanca();
        }
        else{
            tempConta = new ContaSalario();
        }
        tempConta.setNumero(Integer.parseInt(txtContNum.getText()));
        tempConta.setSenha(passConta.getText());
        if(bntAtv.isSelected()){
            tempConta.setAtivo('A');
        }else tempConta.setAtivo('I');
        Cliente tempCl = dtCl.buscar(txtContaTitu.getText());
        Agencia tempAg = dtAg.buscar(Integer.parseInt(txtContaAg.getText()));
        tempCl.setAgencia(tempAg);
        tempConta.setAgencia(tempAg);
        tempConta.addTitular(tempCl);
        dtCt.cadastrar(tempConta);
        setIn();
        limpar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void listClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listClienteActionPerformed
        setIn();
        StringBuilder strB = new StringBuilder();
        for(Cliente c: dtCl.getlClientes()){
            strB.append(c.toString()+"\n");
        }
        txtListar.setText(strB.toString());
        pListar.setVisible(true);
    }//GEN-LAST:event_listClienteActionPerformed

    private void listFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listFuncActionPerformed
        setIn();
        StringBuilder strB = new StringBuilder();
        for(Funcionario f: dtFc.getlFuncionario()){
            strB.append(f.toString()+"\n");
        }
        txtListar.setText(strB.toString());
        pListar.setVisible(true);
    }//GEN-LAST:event_listFuncActionPerformed

    private void passCtOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passCtOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passCtOActionPerformed

    private void sacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacaActionPerformed
        this.flag = 1;
        setIn();
        jLabel28.setVisible(true);
        jLabel29.setVisible(true);
        txtCtO.setVisible(true);
        passCtO.setVisible(true);
        jLabel27.setVisible(false);
        txtCtD.setVisible(false);
        pSacDep.setVisible(true);
    }//GEN-LAST:event_sacaActionPerformed

    private void depositaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositaActionPerformed
        this.flag = 2;
        setIn();
        jLabel28.setVisible(false);
        jLabel29.setVisible(false);
        txtCtO.setVisible(false);
        passCtO.setVisible(false);
        jLabel27.setVisible(true);
        txtCtD.setVisible(true);
        pSacDep.setVisible(true);
    }//GEN-LAST:event_depositaActionPerformed

    private void transfereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transfereActionPerformed
        this.flag = 3;
        setIn();
        jLabel28.setVisible(true);
        jLabel29.setVisible(true);
        txtCtO.setVisible(true);
        passCtO.setVisible(true);
        jLabel27.setVisible(true);
        txtCtD.setVisible(true);
        pSacDep.setVisible(true);
    }//GEN-LAST:event_transfereActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if(this.flag==1){
            Conta tempC = dtCt.buscar(Integer.parseInt(txtCtO.getText()));
            if(passCtO.getText().equals(tempC.getSenha())){
                tempC.sacar(Float.parseFloat(txtValor.getText()));
            }
        }else if(this.flag==2){
            Conta tempC = dtCt.buscar(Integer.parseInt(txtCtD.getText()));
            tempC.depositar(Float.parseFloat(txtValor.getText()));
        }else{
            Conta tempC = dtCt.buscar(Integer.parseInt(txtCtO.getText()));
            if(passCtO.getText().equals(tempC.getSenha())){
                Conta tempD = dtCt.buscar(Integer.parseInt(txtCtD.getText()));
                tempC.transferencia(Float.parseFloat(txtValor.getText()), tempD);
            }
        }
        setIn();
        limpar();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnAttCtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttCtActionPerformed
        this.flag = 10;
        setIn();
        lblRm.setText("Numero da Conta:");
        pRemover.setVisible(true);
    }//GEN-LAST:event_btnAttCtActionPerformed

    private void btnAttFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttFActionPerformed
        this.flag = 12;
        setIn();
        lblRm.setText("CPF do Funcionario:");
        pRemover.setVisible(true);
    }//GEN-LAST:event_btnAttFActionPerformed

    private void btnAttClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttClActionPerformed
        this.flag = 11;
        setIn();
        lblRm.setText("CPF do Cliente:");
        pRemover.setVisible(true);
    }//GEN-LAST:event_btnAttClActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        this.flag = 13;
        setIn();
        pCadAgencia.setVisible(true);
    }//GEN-LAST:event_jButton14ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Front.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Front().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bntAtv;
    private javax.swing.JButton btnAttCl;
    private javax.swing.JButton btnAttCt;
    private javax.swing.JButton btnAttF;
    private javax.swing.JButton btnCadAgn;
    private javax.swing.JRadioButton btnFuncGer;
    private javax.swing.JRadioButton btnH;
    private javax.swing.JRadioButton btnIn;
    private javax.swing.JRadioButton btnM;
    private javax.swing.JButton btnPE;
    private javax.swing.JButton btnRm;
    private javax.swing.JRadioButton btnTCorr;
    private javax.swing.JRadioButton btnTPou;
    private javax.swing.JRadioButton btnTSal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cadCliente;
    private javax.swing.JButton cadConta;
    private javax.swing.JButton cadFunc;
    private javax.swing.JButton deposita;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRm;
    private javax.swing.JButton listCliente;
    private javax.swing.JButton listConta;
    private javax.swing.JButton listFunc;
    private javax.swing.JPanel pCadAgencia;
    private javax.swing.JPanel pCadConta;
    private javax.swing.JPanel pCadEndereco;
    private javax.swing.JPanel pCadFunc;
    private javax.swing.JPanel pCadPessoa;
    private javax.swing.JPanel pCliente;
    private javax.swing.JPanel pConta;
    private javax.swing.JPanel pFunc;
    private javax.swing.JPanel pListar;
    private javax.swing.JPanel pRemover;
    private javax.swing.JPanel pSacDep;
    private javax.swing.JPasswordField passConta;
    private javax.swing.JPasswordField passCtO;
    private javax.swing.JButton saca;
    private javax.swing.JButton salvCliente;
    private javax.swing.JButton salvConta;
    private javax.swing.JButton salvFunc;
    private javax.swing.ButtonGroup sex;
    private javax.swing.JButton transfere;
    private javax.swing.JTextField txtAgcGer;
    private javax.swing.JTextField txtAgcNome;
    private javax.swing.JTextField txtAgcNum;
    private javax.swing.JTextField txtContNum;
    private javax.swing.JTextField txtContaAg;
    private javax.swing.JTextField txtContaTitu;
    private javax.swing.JTextField txtCtD;
    private javax.swing.JTextField txtCtO;
    private javax.swing.JTextField txtDtAdm;
    private javax.swing.JTextField txtEndBai;
    private javax.swing.JTextField txtEndCEP;
    private javax.swing.JTextField txtEndCdd;
    private javax.swing.JTextField txtEndLog;
    private javax.swing.JTextField txtEndNum;
    private javax.swing.JTextField txtEndUF;
    private javax.swing.JTextField txtEstCivil;
    private javax.swing.JTextField txtFuncCTPS;
    private javax.swing.JTextField txtFuncCargo;
    private javax.swing.JTextArea txtListar;
    private javax.swing.JTextField txtPessCPF;
    private javax.swing.JTextField txtPessDt;
    private javax.swing.JTextField txtPessEsc;
    private javax.swing.JTextField txtPessNome;
    private javax.swing.JTextField txtPessTel;
    private javax.swing.JTextField txtRemove;
    private javax.swing.JTextField txtValor;
    private javax.swing.ButtonGroup typeConta;
    // End of variables declaration//GEN-END:variables
}
